name: Download uYou DEB

on:
  workflow_dispatch:
    inputs:
      UYOU_VERSION:
        description: 'uYou Version'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests

    - name: Download file
      run: |
        cat << 'EOF' > download_script.py
        from selenium import webdriver
        from selenium.webdriver.chrome.service import Service
        from selenium.webdriver.chrome.options import Options
        from selenium.webdriver.support.ui import WebDriverWait
        from selenium.webdriver.support import expected_conditions as EC
        from webdriver_manager.chrome import ChromeDriverManager
        import os
        import time
        import requests

        def download_file():
            version = os.environ['UYOU_VERSION']
            url = f"https://miro92.com/repo/debs/com.miro.uyou_{version}_iphoneos-arm.deb"
            
            # Setup Chrome options
            chrome_options = Options()
            chrome_options.add_argument('--headless')
            chrome_options.add_argument('--no-sandbox')
            chrome_options.add_argument('--disable-dev-shm-usage')
            
            # Initialize the Chrome driver
            driver = webdriver.Chrome(
                service=Service(ChromeDriverManager().install()),
                options=chrome_options
            )
            
            try:
                # Visit the page
                driver.get(url)
                
                # Wait for Cloudflare check (at least 5 seconds)
                time.sleep(7)
